### ISSUE TITLE
Proposal to swap deprecated request for node-fetch

### ISSUE THREAD

**Issue by OliverMKing** [kubernetes-client/javascript#754]
# Proposal to swap deprecated request for node-fetch

Request is fully deprecated requiring us to switch libraries (see #414 for more information).

@brendanburns outlined some of the clear options [forward](https://github.com/kubernetes-client/javascript/issues/414#issuecomment-978031677). This change should ideally be a long-term solution leaving us with the option of either modifying the node-typescript open-api-generator to use a different request library or migrate to one of the other generator options.

Modifying an outdated node-typescript library does not seem like the right path forward. It would require us to still use a new library which would likely change the api and still be a breaking change. We might as well migrate to a newer version of openapi-generator while we do that and acquire the advantages of a more up-to-date version.

## Choosing a new library

@d-cs posted a nice [summary](https://github.com/kubernetes-client/javascript/issues/414#issuecomment-648847415) of the different choices. We narrowed it down to Axios or Fetch. The other libraries didn't match how widely adopted and focused these libraries are.

Fetch is simply the standard JavaScript as a whole is moving to, which brings more longterm support aligning us better with our goal of migrating to a long-term solution. [node-fetch](https://www.npmjs.com/package/node-fetch) has significantly more weekly downloads than [axios](https://github.com/axios/axios). The package size of node-fetch is also noticeably smaller than axios.

Additionally, future improvements could likely be done to allow us to also support the browser #165 since Fetch is native to the browser.

## Node-fetch

Fetch is a native browser API that is not implemented in Node.js by default. Node-fetch is the natural choice for the Node implementation because it is the most widely adopted.

The openapi-generator uses the browser implementation of Fetch so we must substitute node-fetch in manually.

## Implementation steps

@davidgamero and I will work to implement the following changes.

### Other repositories

-   [x] Update [kubernetes-client/gen](https://github.com/kubernetes-client/gen)'s typescript-fetch files to let us pass in the `typescriptThreePlus` config option <sup>[1](https://github.com/OpenAPITools/openapi-generator/issues/9973) [2](https://github.com/OpenAPITools/openapi-generator/issues/3869#issuecomment-584152932)</sub>
-   [x] Update [openapi-generator](https://github.com/OpenAPITools/openapi-generator)'s typescript-fetch flavor to mark parameters as optional if all parameters are optional <sup>[3](https://github.com/OpenAPITools/openapi-generator/issues/6440)</sup>

### Kubernetes-client repository

-   [x] Increment `OPENAPI_GENERATOR_COMMIT` to be [version 5.3.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.3.0)
-   [x] `npm install node-fetch` to install node-fetch
-   [x] Switch generate-client script to use typescript-fetch
-   [x] Import and inject node-fetch in `src/api.ts` with the following

```typescript
import fetch from 'node-fetch';

// inject node-fetch
if (!globalThis.fetch) {
    // @ts-ignore
    globalThis.fetch = fetch;
    globalThis.Headers = Headers;
    globalThis.Request = Request;
    globalThis.Response = Response;
}
```

-   [x] Generate api with `npm run generate`
-   [x] Match src/gen/api.ts to new generated layout (it changes slightly)
-   [x] Fix errors in /src folder (due to new api)
-   [ ] Fix errors in test (due to new api)
-   [ ] Fix examples (due to new api)
-   [ ] Document breaking changes for users
-   [ ] Release new version

**Comment by brendandburns** [comment]
This approach is going to introduce breaking changes for consumers of this client library (there were 151k downloads last week alone).

We need to have a more careful plan for how we roll out this change.

I would like to support existing users for at least a few versions (perhaps 3?) while we make this transition.

Perhaps the right way to do this is to introduce a new major version to signify the new generator?

e.g.

`0.17.x` == old generator, Kubernetes 1.23 API
`0.18.x` == old generator, Kubernetes 1.24 API
`0.19.x` == old generator, Kubernetes 1.25 API
Support for old generator stops after 1.25

`1.0.x` == new generator, Kubernetes 1.23 API
`1.1.x` == new generator, Kubernetes 1.24 API
`1.2.x` == new generator, Kubernetes 1.25 API
Support for subsequent kubernetes versions continues with the new generator.

This will require introducing a new branch for the `1.x` series of releases, that's probably going to be necessary anyway since we don't want to make this change in a single PR.

Please note that this is going to be a _big_ change that will touch nearly the entire library, I think

**Comment by OliverMKing** [comment]
That phasing plan makes sense to me. It's in-line with the [npm semantic versioning](https://docs.npmjs.com/about-semantic-versioning).

It might make sense to [deprecate](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) the 0.x releases with a warning telling them that support for the old client api will no longer be supported after a certain version and encouraging them to upgrade. That should alert existing users of the changes.

I'm prepared to take on the responsibility associated with this upgrade.

**Comment by dominykas** [comment]
Is using both generators and fetch/request in parallel not an option during the transition? I haven't thought through all implications or the workload of doing that, just thinking out loud, but it would be nice if you could do something like `makeApiClient(CoreV1Api, { fetch: true })` for the next 3 releases or smth, and only do the breaking change then?

**Comment by davidgamero** [comment]
I agree it would be nice if we could keep the user experience that cohesive, but unfortunately these changes seem too broad and breaking for that to be doable. Given the extent of the proposed changes, it could introduce significant overhead and complexity to have two major versions bundled in a single release.

I've taken a shot at incrementing `OPENAPI_GENERATOR_COMMIT` as proposed, and it appears that several response types have changed, an example is the removals of the `.body` properties ex:

`(await api.listNamespacedPod(namespace)).body` -> `(await api.listNamespacedPod({ namespace }))`

Another predictable area of major changes is the error interfaces since we are changing the network library, and the proposal includes incrementing typescript by a major version.

This may be a config option that I've inadvertently changed, but IMO it does come across cleaner.

This could be a concern if we had `{ fetch: true }` as an option, since the option wouldn't just change functionality under the hood, but also several parts of the api interfaces.

I'll keep checking it out. There could be an easier way tweaking the generator options that I'm not familiar with.

**Comment by brendandburns** [comment]
One other option would be to package the old generated code and the new generated code into different directories and effectively have:

`import api_old from @kubernetes/node-client`

or

`import api_new from @kubernetes/node-client`

e.g. keep everything in one place from a release perspective, but introduce a fork in the imports that you can use.

**Comment by davidgamero** [comment]
That could definitely work if we introduce a named export for `api_old`. I'm not sure how we could do that without potentially breaking existing default import compatibility unless we nest the `api_new` inside it.

Another possibility would be to have 

`import api_old from @kubernetes/node-client`

or

`import api_new from @kubernetes/node-client/fetch`

to retain existing import compatibility for `import k8s from @kubernetes/node-client`

1. Current Top Level Exports 
 
```
@kubernetes/node-client
├── CoreV1Api
...
└── KubeConfig
```

```
// Named Level Exports 
// `import { api_new } from @kubernetes/node-client`
// `import { api_old } from @kubernetes/node-client`
// `import k8s from @kubernetes/node-client` <- no longer works, points to { api_old , api_new }
@kubernetes/node-client
├── api_old
│    ├─ CoreV1Api
│    ...
│    └─ KubeConfig
│
└── api_new
     ├─ CoreV1Api
     ...
     └─ KubeConfig
```

```
// Messy Nested Export
// `import { api_new } from @kubernetes/node-client`
// `import { api_old } from @kubernetes/node-client`
// `import k8s from @kubernetes/node-client` <- works still, but gross way to do it
@kubernetes/node-client
├── CoreV1Api
...
├── KubeConfig
└── api_new
     ├─ CoreV1Api
     ...
     └─ KubeConfig
```

**Comment by brendandburns** [comment]
I think there are different kinds of breaking changes. I feel like changing an import statement is a much lower cost breaking change vs changing the entire API surface area. So I would be ok to require

`import { api_new as api } from @kubernetes/node-client`

or

`import { api_old as api } from @kubernetes/node-client`

And I think that is feasible...

**Comment by OliverMKing** [comment]
I don't think putting both the new api and old api in the same package / directory makes sense to me. 

The fact that it's a breaking change between them means that someone can't just swap out API's when making the change.
```typescript
// switching from this
import { api_new as api } from @kubernetes/node-client
// to this would still require code changes in lots of places where the api is used
import { api_old as api } from @kubernetes/node-client
```
Someone migrating to the new api would have to change every single node-client import statement in their repo which would be time consuming and tedious. It's simpler from a user-standpoint to simply upgrade their version then fix any errors in the code.

By having both the old and new api in the same package we also wouldn't be able to take advantage of a npm deprecation warning which would help warn users of the upcoming drop of support for the old api.

Users wouldn't be upgraded to the breaking api without doing it manually (or changing their `package.json` to allow for major release updates) due to [npm semantic versioning](https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json). 

From a user-standpoint I don't think it's easier to change the import and I believe one of our goals should be gently pushing consumers to migrate when they get the chance (or at least be aware of upcoming drops in support). From our standpoint it's more difficult to work with a directory layout that has two apis rather than just different branches.

**Comment by davidgamero** [comment]
The [major version suggestion](https://github.com/kubernetes-client/javascript/issues/754#issuecomment-990382658) seems be the cleanest way.

Putting the changes in a new major version would make upgrading a clear decision without interfering with existing code.

That way we don't mix code from two generators in a single package.

**Comment by ivanstanev** [comment]
Completely supporting the major version upgrade. Our team doesn't mind spending some time adjusting code to the new API, as long as we can stop using deprecated or regularly vulnerable packages! 😄

**Comment by brendandburns** [comment]
Ok, sounds like the consensus is for a major version upgrade. I have created a `release-0.x` branch, which we will use for the releases of the old generated client for the next ~9 months.

We can start sending PRs to the `master` branch now to start making these changes.

**Comment by brendandburns** [comment]
We should also probably turn this discussion into a markdown document that describes our approach and links off of the main README.md

**Comment by OliverMKing** [comment]
Quick update: @davidgamero and I have been working on this for the last two weeks. We're having to make some changes to open-api generator to support the way we need to do auth. @davidgamero has been working on identifying the exact improvements necessary.

**Comment by davidgamero** [comment]
Update 2: Two PRs have been completed against OpenAPITools/openapi-generator (the typescript generator template in specific), and a third is in progress.

Complete (PR)
- [[typescript] Default auth method support and optional param object when all params optional](https://github.com/OpenAPITools/openapi-generator/pull/11321)
- [useSingleRequestParameter should mark parameter optional if all properties are optional](https://github.com/OpenAPITools/openapi-generator/pull/11135)

In Progress (Issue) [[REQ][typescript] Enable passing custom SecurityAuthentication to API](https://github.com/OpenAPITools/openapi-generator/issues/11394)

With this last PR, the ability to pass certificates to the  `fetch` client should be exposed in the typescript generator, clearing the way for fullAuth migration

**Comment by davidgamero** [comment]
Update 3: Custom Authentication is now complete in the typescript generator. Currently migrating the `request` implementations outside the generated code (in /src)

https://github.com/OpenAPITools/openapi-generator/pull/11400

**Comment by loynoir** [comment]
fetch

- node >=17.5.0 has `--experimental-fetch`, which is using undici
- node > 16, has undici support
- node < 16, maybe fallback to node-fetch

https://nodejs.org/en/blog/release/v17.5.0/

> Adds experimental support to the fetch API. This adds a --experimental-fetch flag that installs the fetch, Request, Response and Headers globals.

node 17's fetch is using undici

https://github.com/nodejs/node/commit/76a229c4ff

**Comment by OliverMKing** [comment]
> fetch
> 
> * node >=17.5.0 has `--experimental-fetch`, which is using undici
> * node >= 16, has undici support
> * node < 16, maybe fallback to node-fetch
> 
> https://nodejs.org/en/blog/release/v17.5.0/
> 
> > Adds experimental support to the fetch API. This adds a --experimental-fetch flag that installs the fetch, Request, Response and Headers globals.
> 
> node 17's fetch is using undici
> 
> [nodejs/node@76a229c4ff](https://github.com/nodejs/node/commit/76a229c4ff)

Hopefully the TypeScript generator swaps over to this way.

**Comment by haoxins** [comment]
https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental

**Comment by chadbr** [comment]
Hello,

If I understand correctly - Here:

https://github.com/kubernetes-client/javascript/blob/b4ccd6e6588960edb02b89bc0a3b32e797d71554/FETCH_MIGRATION.md?plain=1#L62

The latest status is:
`Fix errors in /src folder (due to new generated api)`

Is this something I can help with? Is there a branch with source I can help to get compiling, I'm happy to try to help.

Thanks, Chad

**Comment by davidgamero** [comment]
Hi @chadbr , the current working branch is https://github.com/kubernetes-client/javascript/tree/release-1.x and the next step is migrating all the auth providers and their unit tests. It's mostly mapping headers and query params to use the new `RequestContext` ex PR: https://github.com/kubernetes-client/javascript/pull/790/files

Any help migrating those would be very appreciated! I'm finishing up the `log.ts` migration atm as it's one of the last places we still directly call the `request` api outside the generated code. As for auth providers, I only did the `azure_auth` so far, so the rest are all in need of a migration PR

**Comment by dpryden** [comment]
What is the current status of this? It looks like the tests in the `release-1.x` branch are passing. Is the `FETCH_MIGRATION.md` document up to date? What work remains before this branch can be released?

**Comment by davidgamero** [comment]
The scope of the initial release was reduced to get us to a testable state faster, so the `watch` and a couple other kubectl-style wrappers are not fully implemented; however, the generated api parts are all passing tests and functional for a testable release atm.

**Comment by maddie-j** [comment]
Heya, just wondering what tasks there are left before `request` is gone for good? Our team _really_ wants `request` out of our repo with all its associated security risks, so I can probably bug my manager to give me a few days to help out here to get things moving.

**Comment by brendandburns** [comment]
@maddie-j see the comment here:

https://github.com/kubernetes-client/javascript/issues/754#issuecomment-1147618317

The branch is there and generally works but is incomplete. if you want to see if it works for your use-cases and send PRs if it doesn't that will help push things along.

**Comment by dweitzman-codaio** [comment]
There's a new CVE in `request` (https://github.com/advisories/GHSA-p8p7-x288-28g6), so folks who audit their node deps for security issues may notice today that `@kubernetes/client-node` is one of the libraries that still depends on `request`

**Comment by brendandburns** [comment]
For anyone who arrives here from that CVE, there is a 1.x release branch that you can try that uses fetch instead. It is incomplete though (help is welcome!)

**Comment by mstruebing** [comment]
@brendandburns is there a good overview of tasks that needs to be done for that branch to be able to help efficiently?

**Comment by brendandburns** [comment]
@mstruebing much of the core functionality should work, I think the main task would be to go through all of the example code and port it to the new APIs and verify that it all works correctly.

Alternatively, just trying it in your application and seeing if it works correctly and then filing bugs (or fixing them in PRs :) would also be very helpful.

cc @davidgamero who has been mostly driving this effort.

**Comment by davidgamero** [comment]
@mstruebing i just put up a PR with a more detailed update on the status of 1.x release TODOs. I’m continuing work on auth, so the main two open items are ‘src/log.ts’ and ‘src/watch.ts’ need significant engineering to update their async types and implementations to fully remove ‘request’

@brendandburns is correct- the examples also need to be updated to fit the new method signatures, which shouldn’t be too bad with a couple exceptions for examples relying on request manipulation directly.

If you’d like to take any of the items I can start making issues for them and we can manage the remaining work that way. I don’t remember if we have a dedicated release-1.x tag already but that could keep things tidy.

**Comment by Fryuni** [comment]
Since the 1.x branch is working for most operations, would it possible to release a `1.0.0-alpha` flagged as a pre-release on NPM?
This way, those that don't depend only on what is already working may opt to update.

Dependencies to a Git branch don't work when the code is in TypeScript.

**Comment by brendandburns** [comment]
@Fryuni I have just pushed `1.0.0-rc1` out to NPM.

https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc1

Please give it a try and report any issues.

Note that it will require rewriting your client code as the API has changed somewhat.

**Comment by Nokel81** [comment]
I have given it a try for Lens (https://github.com/lensapp/lens/pull/7418), at it works great. Though we don't use any of the authorization flow from the JS library so that might be why we encountered no issues.

**Comment by davidgamero** [comment]
I'm so glad to see that it's working for you!

**Comment by rbnayax** [comment]
> @Fryuni I have just pushed `1.0.0-rc1` out to NPM.
> 
> https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc1
> 
> Please give it a try and report any issues.
> 
> Note that it will require rewriting your client code as the API has changed somewhat.

I see that request is still listed as a dependency, but not being used, is it possible to remove it?

**Comment by brendandburns** [comment]
@rbnayax happy to take a PR to update `package.json` or we'll get to it eventually.

**Comment by rbnayax** [comment]
> @rbnayax happy to take a PR to update `package.json` or we'll get to it eventually.

Gladly - https://github.com/kubernetes-client/javascript/pull/1033

**Comment by Saeger** [comment]
# Feedback, Tests, Considerations
Hi, First of all, thanks for all the hard work here. I have given the RC1 a try here @digitalroute and it have worked mostly for my tests. I would like to provide some considerations as part of the tests and usage as form of contribution to the repo.

# About the breaking change
The breaking change so far are simple to solve TBH (But in our case, all K8S comms are done by one internal module which wraps @kubernetes-client/javascript), this made our life easier and I totally recommend these type of approach when using microservice architecture.
Back to what matters!


# Issues found so far
I have found a couple of issues thought which I would like to ensure I haven't done anything wrong on my side @brendandburns @davidgamero @OliverMKing: 

1. The `patchNamespacedConfigMap` is missing the header parameter. This way, one can't use the `application/strategic-merge-patch+json` header.
2. The `deleteNamespacedService` is now returning a `V1Status` instead of `V1Service`. I guess this was wrong before actually and maybe it was addressed in a future version since we were using 0.18.1, but wanted to confirm this change is not related to RC1.
3. The `patchNamespacedService` and `patchNamespacedCustomObject` have the same issue as #1
4. Not really an issue but I wonder if methods like `createNamespaceCustomObject` will become Promise<any> from now on ? And I will need to assume that it's interface will follow the new ones returning the body only instead of both response & body. I think this needs to be mentioned in the migration documentation somehow?
5. Still a bit related to #4, I think methods like `deleteNamespacedCustomObject` should still return Promise<V1Status> since this follows the pattern of the library, doesn't matter if it's a Customer Object really, the interface of the return message is still the same and shouldn't be changed to Promise<any>
6. I understand that now, since we're moving away from "request" library, the HttpError type is no longer valid. Will we have an alternative? Should this be considered in the migration documentation? My interest in this point is how to understand the HTTP errors thrown by the library so I can track down the 404 for when resources are not found (so we can treat them differently).


I am not sure how should I report these issues that's why I decided to put it here.

# Kudos

I would like to also give some kudos because of the named parameters! No more `"this.namespace, undefined, undefined, undefined, undefined, propagationPolicy"` 💯

**Comment by brendandburns** [comment]
@briandealwis sorry for the delay, an `rc2` has been pushed to npm. Please give it a try.

**Comment by joshperry** [comment]
@pauliusg Problem with `ERR_INVALID_URL` is that when passing in a configuration to a method, it overrides the whole client configuration, and if you create a configuration without specifying a particular property, it uses a default. So the `baseServer` config property get set to a default empty value and the error gets thrown when the URL lib attempts to parse the hostless URL.

I worked around that like this:

```js

const patchconf = client => createConfiguration({
  promiseMiddleware: [
    {
      pre: async (context) => {
        context.setHeaderParam('Content-type', k8s.PatchUtils.PATCH_FORMAT_JSON_PATCH);
        return context;
      },
      post: async (context) => {
        return context;
      },
    },
  ],
  baseServer: client.api.configuration.baseServer,
});
```

The problem here is that when this error is resolved, the media type error returns. Turns out that problem is caused by a bug in the generated code that _can't_ be worked around.

In the action method it attempts to automate the request content-type selection:

```js
        // Body Params
        const contentType = ObjectSerializer_1.ObjectSerializer.getPreferredMediaType([
            "application/json-patch+json",
            "application/merge-patch+json",
            "application/strategic-merge-patch+json",
            "application/apply-patch+yaml"
        ]);
```

That function looks like this:

```js
const supportedMediaTypes = {
    "application/json": Infinity,
    "application/octet-stream": 0,
    "application/x-www-form-urlencoded": 0
};

...

    static getPreferredMediaType(mediaTypes) {
        /** According to OAS 3 we should default to json */
        if (mediaTypes.length === 0) {
            return "application/json";
        }
        const normalMediaTypes = mediaTypes.map(this.normalizeMediaType);
        let selectedMediaType = undefined;
        let selectedRank = -Infinity;
        for (const mediaType of normalMediaTypes) {
            if (supportedMediaTypes[mediaType] > selectedRank) {
                selectedMediaType = mediaType;
                selectedRank = supportedMediaTypes[mediaType];
            }
        }
        if (selectedMediaType === undefined) {
            throw new Error("None of the given media types are supported: " + mediaTypes.join(", "));
        }
        return selectedMediaType;
    }
```

I think it _should_ be obvious why this is doomed to permanently fail...

I've spent half the day working on getting a local dev setup to iterate on a potential fix, but haven't yet succeeded. Until then, I've told my security people that the package update date is unfortunately indeterminate.

**Comment by brendandburns** [comment]
@joshperry if the bug is indeed in the generated code, the code generator is here:

https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/typescript-fetch

They're usually pretty good about merging fixes, and then we can regenerate.

**Comment by davidgamero** [comment]
which media type are you missing? it's possible we just need to bump the gen hash to include https://github.com/OpenAPITools/openapi-generator/pull/16386

**Comment by joshperry** [comment]
Looks like this issue was already fixed and merged upstream, just waiting for a new release: https://github.com/OpenAPITools/openapi-generator/pull/16386
local issue: https://github.com/kubernetes-client/javascript/issues/893

I guess the only other issue (for `patch*`) is the ergonomics of applying a custom header. With the upstream fix, at least patch routes and the middleware option will work, but replacing the whole request config (instead of merging, or separating params) when calling a client's method doesn't feel right, as does reaching deep into the client's state to do the merge yourself.

**Comment by davidgamero** [comment]
@joshperry do you mean waiting for a release from openapi-generator or this project?
if you mean openapi we can just bump the hash we use- we don't build using their releases

**Comment by davidgamero** [comment]
i completely agree that the ergonomics of the custom header are cumbersome for this use case, and providing a way to merge new options into the config would make this much easier

**Comment by davidgamero** [comment]
the middleware workaround seems reasonable while we develop a cleaner long-term solution, so im in favor of a new rc with that code included. just made a pr for the changes @joshperry

**Comment by kberkos-public** [comment]
Bumping up the priority on this item, since the deprecated `Request` Package now has a security vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2023-28155

**Comment by efenner-cambia** [comment]
Any update on this? Very interested in closing out the CVE referenced above

**Comment by brendandburns** [comment]
@efenner-cambia there is a pre-release of the library based on fetch that you can start consuming:
https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc3

Note that the API has changed somewhat, so it is not a drop-in replacement.

**Comment by kberkos-public** [comment]
Thank you so much @brendandburns !

**Comment by RSAlderman** [comment]
I can see there's a later pre-release library https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc4?activeTab=versions made available on 2023-12-23. @brendandburns do you know when v1.0.0 is going to be released and in which kubernetes version it will be included, to remediate [CVE-2023-28155](https://github.com/advisories/GHSA-p8p7-x288-28g6)?

**Comment by ArvinB** [comment]
@brendandburns any update on this?

**Comment by brendandburns** [comment]
This client is not released as part of the Kubernetes release. There is no current eta for a non RC 1.0.0 release, we need more mileage and reports from people that they have migrated successfully to have confidence in the release.

**Comment by RSAlderman** [comment]
@brendandburns can you confirm that when kuberenetes/client-node/v/1.0.0 is available as well as remediating [CVE-2023-28155](https://github.com/advisories/GHSA-p8p7-x288-28g6), it will also remediate [CVE-2023-26136](https://github.com/advisories/GHSA-72xf-g2v4-qvf3); where it seems the required upgrade to `tough-cookie-4.1.3` is dependent on the replacement of the `request` package?

PSIRTRef_fup_3P_kubernetes PVR0452658

**Comment by briandealwis** [comment]
I forgot to report that I migrated a private repository to rc2 with no issues.  I didn’t realize that there was an rc3; I’ll add that to my todo list.

**Comment by mstruebing** [comment]
@briandealwis There is even an rc4 by now: https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc4

**Comment by mdouglass** [comment]
Migrated 14 microservices to rc4 with no issues other than one TS type that needed to change (we had cast the watch result `any` in 0.20 to a request type and it needed to be `AbortController` now -- which makes more sense anyway)

**Comment by meda1028** [comment]
> @briandealwis There is even an rc4 by now: https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc4

https://github.com/backstage/backstage/pull/23320

**Comment by RSAlderman** [comment]
The latest pre-release library https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc4?activeTab=versions remains rc4 made available on 2023-12-23, which appears to be receiving positive feedback for migrating microservices.
 
Is there any further thought when v1.0.0 maybe released and in which kubernetes version it will be included? I believe this is blocking the remediation of [CVE-2023-28155](https://github.com/advisories/GHSA-p8p7-x288-28g6) as well as [CVE-2023-26136](https://github.com/advisories/GHSA-72xf-g2v4-qvf3), where it seems the required upgrade to tough-cookie-4.1.3 is dependent on the replacement of the request package.

PSIRTRef_fup_3P_kubernetes PVR0429050 PVR0452658 PVR0473928

**Comment by pauliusg** [comment]
I wouldn't say that rc4 feedback is positive. Yes, code works properly but it is a pain to use middleware. For example when you need to add a header when patching pod:
```
import * as k8s from '@kubernetes/client-node';

...

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const headerPatchMiddleware = new PromiseMiddlewareWrapper({
  pre: async (requestContext) => {
    requestContext.setHeaderParam('Content-type', 'application/json-patch+json');
    return requestContext;
  },
  post: async (responseContext) => responseContext,
});

const currentCluster = kc.getCurrentCluster();
if (!currentCluster) {
  throw new HandledException('Kube config does not have current cluster.');
}

const server = currentCluster.server;
if (!server) {
  throw new Error('Kube config cluster does not have server.');
}

const baseServerConfig: k8s.ServerConfiguration<Record<string, never>> =
  new k8s.ServerConfiguration<Record<string, never>>(server, {});
const k8sPatchPodConfiguration = k8s.createConfiguration({
  middleware: [headerPatchMiddleware],
  baseServer: baseServerConfig,
  authMethods: { default: kc },
});

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

...

const patch = [
  {
    op: 'replace',
    path: '/metadata/annotations',
    value: annotationsObject,
  },
];

await k8sApi.patchNamespacedPod(
  {
    name: podName,
    namespace: namespace,
    body: patch,
  },
  k8sPatchPodConfiguration,
);

```
I think you agree that we need quite much code to patch a pod, it should be simpler...

**Comment by sergi** [comment]
Just pointing out that [fetch **is** implemented natively in Node.js](https://nodejs.org/docs/latest-v22.x/api/globals.html#fetch), and it's been available since Node 18 (so it includes current and previous LTS, so strictly there's no need to use `node-fetch`. Of course, if the project wants to support earlier versions of Node.js, then `node-fetch` makes sense.

**Comment by lachieh** [comment]
Node 16 went EOL in September of 2023, so it's doesn't really feel valuable supporting it—especially since the standard k8s support window is only 14 months. Is there interest from the @maintainers team in going straight to the node implementation of fetch or is the plan to stick with node-fetch?

**Comment by mstruebing** [comment]
I would think we should start with finishing the `node-fetch` implementation.
Later on we can change that to the native fetch implementation. That shift should be significant easier than the move from `request` to `node-fetch`

**Comment by cjihrig** [comment]
@mstruebing do you think this issue can be closed since v1.0.0 was released with node-fetch?

**Comment by dastrobu** [comment]
is v1.0.0 released already? I don't find it under: [1.0.0](https://github.com/kubernetes-client/javascript/tree/1.0.0), there is only [1.0.0-rc5](https://github.com/kubernetes-client/javascript/tree/1.0.0-rc5).

**Comment by mstruebing** [comment]
@dastrobu we have had an issue with our GitHub action so the release did not get tagged on GitHub.
It’s available via npm.
We could manually push that tag to GitHub and create a GitHub release.
I will do that later if I can find out the exact commit hash.

**Comment by brendandburns** [comment]
Thanks for the patience, added the tag at the appropriate commit:

https://github.com/kubernetes-client/javascript/releases/tag/1.0.0

**Comment by cjihrig** [comment]
Closing, as the swap happened.

/close
